name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install black pytest
          
      - name: Debug env
        run: |
          python -V
          pip list
          ls -la
          find . -maxdepth 3 -type f \( -name "*.py" -o -name "requirements.txt" \) | sort

      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CI_FAKE_MODEL: "1"
          PYTHONPATH: ${{ github.workspace }}

        run: |
          pytest -q -k test_basic -vv

      - name: Debug tree
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type d -name "meeting_policy_checker" -print



